base_model: "meta-llama/Meta-Llama-3-8B-Instruct"   # or "mistralai/Mistral-7B-Instruct-v0.3"
output_dir: "outputs/social_only"
seed: 42

# data
datasets:
  reddit_tifu: { use: true, subset: "long", split: "train" }  # "short" has TL;DR
  tweetsumm:   { use: false, path: "data/tweetsumm.jsonl" }    # optional local JSONL

max_source_len: 2048
max_target_len: 96
train_ratio: 0.97
val_ratio: 0.03

# sampling / curriculum
sampling:
  use_domain_tags: true
  social_to_news_ratio: [1.0, 0.0]  # social only

# training
bf16: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 16
num_train_epochs: 2
learning_rate: 2.0e-4
weight_decay: 0.01
warmup_ratio: 0.05
lr_scheduler_type: "cosine"
save_steps: 1000
eval_steps: 1000
logging_steps: 50
gradient_checkpointing: true
max_steps: -1

# lora
lora:
  enabled: true
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  target_modules: ["q_proj","k_proj","v_proj","o_proj","gate_proj","up_proj","down_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"
